---

- hosts: all
  when: ansible_virtualization_type == "parallels" and ansible_virtualization_role == "guest"
  vars:
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"

  tasks:
    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: "present"
        update_cache: yes
      with_items:
         - linux-headers
         - dkms
         - python2

    - name: Create link to python
      file: src="/usr/bin/python2"
            dest="/usr/bin/python"
            state="link"

    - name: Touch xorg.con
      command: "touch /etc/X11/xorg.conf"

    - name: download prl-tools-lin.iso
      get_url:
        url: http://uo.mf-cdn.ru/d/eyJ0IjoiMjAxNi0xMS0xNlQxMDoyNzo1MS4xNzk0OTE2WiIsInRtIjoxNSwiYmQiOjEsImZkIjoxNzE1NTgwLCJzbCI6MCwiZm4iOiJwcmwtdG9vbHMtbGluLmlzbyIsInIiOiJodHRwOi8vbXktZmlsZXMucnUvajJxdXhsIiwibCI6bnVsbH0,.21A2E1F21DE54CE846D4E767B517C3A6./prl-tools-lin.iso
        dest: /root/prl-tools-lin.iso
        mode: 0440

    - name: Mount ISO
      mount:
        name: "/mnt"
        src: "/root/prl-tools-lin.iso"
        fstype: "iso9660"
        state: "present"

    - name: Create link to init.d
      file: src="/usr/lib/systemd/scripts/"
            dest="/etc/init.d"
            state="link"

    - name: Rebuild kernel
      command: "/mnt/install"