---

- hosts: all

  vars:
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"

  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
         upgrade: yes

    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: "present"
        update_cache: yes
      with_items:
         - linux-headers
         - dkms
         - python2

    - name: Create link to python
      file: src="/usr/bin/python2"
            dest="/usr/bin/python"
            state="link"

    - name: Create link to init.d
      file: src="/usr/lib/systemd/scripts/"
            dest="/etc/init.d"
            state="link"

    - name: Touch xorg.con
      command: "touch /etc/X11/xorg.conf"

    - name: download prl-tools-lin.iso
      get_url:
        url: http://o8.mf-cdn.ru/d/eyJ0IjoiMjAxNi0xMS0xOFQxMjowNDowNi45MjI2NzQ3WiIsInRtIjoxNSwiYmQiOjEsImZkIjoxNzE1NTgwLCJzbCI6MCwiZm4iOiJwcmwtdG9vbHMtbGluLmlzbyIsInIiOiJodHRwOi8vbXktZmlsZXMucnUvajJxdXhsIiwibCI6bnVsbH0,.8430E17A09083A3A90D674DBA3531C67./prl-tools-lin.iso
        dest: /root/prl-tools-lin.iso
        mode: 0440

    - name: Mount ISO
      command: "mount -O loop /root/prl-tools-lin.iso /mnt/"

    - name: Mount ISO
      command: "echo 'go to /mnt^ and run ./install'"