---

- hosts: mothership
  vars:
    ansible_connection: local
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"
  sudo: false
  user: system
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes
      sudo: true

    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: "present"
        update_cache: yes
      with_items:
         - linux-headers
         - dkms
         - python2
      sudo: true

    - name: Create link to python
      file: src="/usr/bin/python2"
            dest="/usr/bin/python"
            state="link"
      sudo: true

    - name: Create link to init.d
      file: src="/usr/lib/systemd/scripts/"
            dest="/etc/init.d"
            state="link"
      sudo: true

    - name: Touch xorg.con
      command: "touch /etc/X11/xorg.conf"
      sudo: true

    - name: download prl-tools-lin.iso
      get_url:
        url: http://1h.mf-cdn.ru/d/eyJ0IjoiMjAxNi0xMS0xOFQxNToxMzoxOS4zMzY5OTUwWiIsInRtIjoxNSwiYmQiOjEsImZkIjoxNzE1NTgwLCJzbCI6MCwiZm4iOiJwcmwtdG9vbHMtbGluLmlzbyIsInIiOiJodHRwOi8vbXktZmlsZXMucnUvajJxdXhsIiwibCI6bnVsbH0,.8055A0519B05D9C91C7F1BB61F9DEE48./prl-tools-lin.iso
        dest: /tmp/prl-tools-lin.iso
        mode: 0440
      sudo: true

    - name: Mount ISO
      command: "mount -o loop /tmp/prl-tools-lin.iso /mnt"
      sudo: true

    - name: Mount ISO
      command: "echo 'go to /mnt and run ./install'"
      sudo: true