---

- hosts: mothership
  vars:
    ansible_connection: local
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"
  sudo: false
  user: system
  tasks:
    - name: Update Arch
      pacman:
        update_cache: yes
        upgrade: yes
      sudo: true

    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: "present"
        update_cache: yes
      with_items:
         - linux-headers
         - dkms
         - python2
      sudo: true

    - name: Touch xorg.con
      command: "touch /etc/X11/xorg.conf"
      sudo: true

    - name: Download prl-tools-lin.iso
      get_url:
        url: http://1z.mf-cdn.ru/d/eyJ0IjoiMjAxNi0xMS0xOFQyMDozMjoxNC4zNzgzMzM5WiIsInRtIjoxNSwiYmQiOjEsImZkIjoxNzE1NTgwLCJzbCI6MCwiZm4iOiJwcmwtdG9vbHMtbGluLmlzbyIsInIiOiJodHRwOi8vbXktZmlsZXMucnUvajJxdXhsIiwibCI6bnVsbH0,.C55A292B0563AC8010ECB77908105905./prl-tools-lin.iso
        dest: "/tmp/prl-tools-lin.iso"
        mode: 0440
      sudo: true

    - name: Mount ISO
      command: "mount -o loop /tmp/prl-tools-lin.iso /mnt"
      sudo: true