---

- name: vbox | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - virtualbox-guest-iso
    - virtualbox-guest-utils
    - virtualbox-guest-dkms
  notify: "grub mkconfig"
  sudo: true

- name: vbox | Disable i2c_piix4
  copy:
    src: "modprobe.d/blacklist.conf"
    dest: "/etc/modprobe.d/blacklist.conf"
  notify: "mkinitcpio"
  sudo: true

- name: vbox | Load VirtualBox module
  copy:
    src: "modules-load.d/virtualbox.conf"
    dest: "/etc/modules-load.d/virtualbox.conf"
  notify: "mkinitcpio"
  sudo: true

- name: vbox | Start services vboxservice
  service:
    name: "vboxservice.service"
    enabled: yes
  sudo: true