---

- name: vbox | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - virtualbox-guest-utils
  notify: "grub mkconfig"
  sudo: true

- name: vbox | Start services vboxservice
  service:
    name: "vboxservice.service"
    enabled: yes
  sudo: true