---

- name: vbox | Update Arch
  pacman:
    update_cache: yes
    upgrade: yes
  sudo: true

- name: vbox | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - virtualbox-guest-utils
    - virtualbox-guest-modules-arch
  sudo: true

- name: Config VirtualBox
  copy:
    src: "virtualbox.conf"
    dest: "/etc/modules-load.d/virtualbox.conf"
  sudo: true

- name: Start services vboxservice
  service:
    name: "vboxservice.service"
    enabled: yes
  sudo: true