---

- name: vbox | Update Arch
  pacman:
    update_cache: yes
    upgrade: yes
  sudo: true

- name: vbox | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - virtualbox-guest-utils
  sudo: true

- name: Config VirtualBox #Magic
  copy:
    src: "virtualbox.conf"
    dest: "/etc/modprobe.d/virtualbox.conf"
  sudo: true

- name: Config /etc/default/grub #Magic
  lineinfile:
    dest: "/etc/default/grub"
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet iomem=relaxed"'
    state: "present"
  sudo: true

- name: grub reconf #Magic
  shell: "grub-mkconfig -o /boot/grub/grub.cfg"
  sudo: true

- name: Start services vboxservice
  service:
    name: "vboxservice.service"
    enabled: yes
  sudo: true