---

- name: vbox | Update Arch
  pacman:
    update_cache: yes
    upgrade: yes
  sudo: true

- name: vbox | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - virtualbox-guest-utils
  sudo: true

- name: vbox | Touch xorg.con
  command: "echo 'vboxguest' '\n' 'vboxsf' '\n' 'vboxvideo' > /etc/modules-load.d/virtualbox.conff"
  sudo: true