---

- name: vbox | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - virtualbox-guest-utils
  sudo: true

- name: vbox | Config VirtualBox #Magic
  copy:
    src: "virtualbox.conf"
    dest: "/etc/modprobe.d/virtualbox.conf"
  sudo: true

- name: vbox | grub-mkconfig #Magic
  shell: "grub-mkconfig -o /boot/grub/grub.cfg"
  sudo: true

- name: vbox | Start services vboxservice
  service:
    name: "vboxservice.service"
    enabled: yes
  sudo: true