---

- hosts: mothership
  vars:
    ansible_connection: local
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"
  sudo: false
  user: system

  handlers:
    #- name: mkinitcpio
    #  command: mkinitcpio -p linux
    #  notify: mkinitcpio-mainline

  tasks:
    - name: Gen facts
      shell: "ansible -m setup all -u mothership > /etc/ansible/facts.yml"
      sudo: true

  roles:
    - base
    - common
    - admin

