---

- hosts: mothership
  vars:
    ansible_connection: local
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"
  sudo: false
  user: system

  handlers:
    - name: locale gen
      shell: locale-gen
      sudo: true

    - name: mkinitcpio
      command: mkinitcpio -p linux
      sudo: true

  tasks:
    - name: Set hostname
      hostname:
        name: "mothership"
      sudo: true

  roles:
    - base
    - vmguest
    - common
    - admin

