---

- hosts: mothership
  vars:
    # Arch's default python is python3
    #ansible_python_interpreter: "/usr/bin/env python2"

  handlers:
    #- name: mkinitcpio
    #  command: mkinitcpio -p linux
    #  notify: mkinitcpio-mainline

  tasks:
    - name: Install python2
      pacman:
        name: "python2"
        state: "present"
        update_cache: yes

  roles:
    - preparation
    - common
