---

- hosts: mothership
  vars:
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"

  handlers:
    - name: mkinitcpio
      command: mkinitcpio -p linux
      notify: mkinitcpio-mainline

  tasks:
    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - base-devel
        - git
        - wget
        - yajl
        - openssh
        - linux-firmware

    - name: Start services (now, and on boot)
      service: state=started name={{ item }} enabled=yes
      with_items:
        - sshd

    - name: command2
      command: "yaourt -S hawaii-meta --noconfirm"

  roles:
    - common
    - gui