---

- name: x-window-system | Install Driver
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - xf86-video-vesa
    - xf86-video-fbdev          # Пакет содержит драйвер для кадрового буфера Linux (еще известный как fbdev).
    - xf86-input-synaptics
    - xf86-video-vmware
    - xf86-input-vmmouse
  sudo: true

- name: x-window-system | Install X system packages
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
    - xorg-twm
    - xorg-xclock
    - xterm
  sudo: true

- name: x-window-system | Install Font
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - ttf-dejavu
    - ttf-droid
    - ttf-inconsolata
  sudo: true

- name: x-window-system | Load VirtualBox module
  copy:
    src: ".xinitrc"
    dest: "/home/admin/.xinitrc"
    owner: admin
    group: users
    mode: 0755
  sudo: true