---

- name: sddm | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - sddm
  sudo: true

- name: sddm | Enable services sddm
  service:
    name: "sddm.service"
    enabled: yes
  sudo: true