---

- name: window-manager | Install window manager
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - openbox
    - obconf
    - obmenu
  sudo: true

- name: window-manager | Create config directory
  file:
    path: "/home/admin/.config/openbox"
    state: "directory"
    owner: "admin"
    group: "users"
    mode: "0755"
  sudo: true

- name: window-manager | Copy config files openbox
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "admin"
    group: "users"
    mode: "0755"
  with_items:
    - { src: "openbox/menu.xml", dest: "/home/admin/.config/openbox/menu.xml" }
    - { src: "openbox/autostart", dest: "/home/admin/.config/openbox/autostart" }
    - { src: "openbox/environment", dest: "/home/admin/.config/openbox/environment" }
  sudo: true

- name: window-manager | Delite /usr/share/xsessions/openbox-kde.desktop
  file:
    state: "absent"
    path: "/usr/share/xsessions/openbox-kde.desktop"
  sudo: true