---

- name: Slim | Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - slim
    - slim-themes
    - archlinux-themes-slim
  sudo: true

#- name: Slim | Copy config
#  copy:
#    src: "slim.conf"
#    dest: "/etc/slim.conf"
#  sudo: true

- name: Slim | Enable services
  service:
    name: "slim.service"
    enabled: yes
  sudo: true