---

- name: xfce4 | Install xfce4
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - xfce4
    - xfce4-goodies
    - xfce4-whiskermenu-plugin
    - archlinux-wallpaper
  sudo: true

- name: xfce4 | Create conf directory for user "admin"
  file:
    path: "/home/admin/.config/xfce4/terminal"
    state: "directory"
    owner: admin
    group: users
  sudo: true

- name: xfce4 | Copy
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: admin
    group: users
    mode: 0755
  with_items:
    - { src: "xfce4/terminal/accels.scm", dest: "/home/admin/.config/xfce4/terminal/accels.scm" }
    - { src: "xfce4/terminal/terminalrc", dest: "/home/admin/.config/xfce4/terminal/terminalrc" }
  sudo: true

- name: Adding existing user "system" to group docker
  shell: "xfconf-query -c xfwm4 -p /general/use_compositing -s false"
  user: admin