---

- name: xfce4 | Install xfce4
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - xfce4
    - xfce4-goodies
    - xfce4-whiskermenu-plugin
    - archlinux-wallpaper
  sudo: true