### Maui project (Hawaii)
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-server-utils
    - xf86-video-vesa
    - lxqt
    - lxqt-common
    - lxqt-config
    - lxqt-panel
    - lxqt-policykit
    - lxqt-qtplugin
    - lxqt-session
    - lxqt-about
    - lxqt-globalkeys
    - lxqt-notificationd
    - lxqt-openssh-askpass
    - lxqt-powermanagement
    - lxqt-runner
    - openbox
    - qterminal
    - breeze-icons
    - sddm

- name: Start services sddm
  service:
    name: "sddm"
    state: "enable"
    enabled: yes
