---

- name: GUI | Install base packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    # Driver
    - xf86-video-vesa
    - xf86-input-synaptics
    # X system
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
    # Font
    - ttf-dejavu
    - ttf-droid
    - ttf-inconsolata
    # WM
    - openbox
    - obconf
    - obmenu
    # Logon
    - sddm
  sudo: true

- name: GUI | Install LXQt packages
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - lxqt
  sudo: true

- name: GUI | Install utills packages
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - firefox
    - terminator

  sudo: true

#- name: GUI | Config /etc/X11/xorg.conf.d/10-monitor.conf
#  copy:
#    src: "10-monitor.conf"
#    dest: "/etc/X11/xorg.conf.d/10-monitor.conf"
#  sudo: true

- name: GUI | Config /etc/X11/xorg.conf.d/50-synaptics.conf
  copy:
    src: "50-synaptics.conf"
    dest: "/etc/X11/xorg.conf.d/50-synaptics.conf"
  sudo: true

- name: GUI | Enable services sddm
  service:
    name: "sddm"
    enabled: yes
  sudo: true
