- name: Install packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - linux-headers
    - dkms
    - python2

- name: Touch xorg.con
  command: "touch /etc/X11/xorg.conf"

- name: download prl-tools-lin.iso
  get_url:
    url: http://vq.mf-cdn.ru/d/eyJ0IjoiMjAxNi0xMS0xNVQyMDoxMToyMy4wNjM2OTc4WiIsInRtIjoxNSwiYmQiOjEsImZkIjoxNzE1NTgwLCJzbCI6MCwiZm4iOiJwcmwtdG9vbHMtbGluLmlzbyIsInIiOiJodHRwOi8vbXktZmlsZXMucnUvajJxdXhsIiwibCI6bnVsbH0,.BBABB2D4B377EAA7D172C60186EAC3F0./prl-tools-lin.iso
    dest: /root/prl-tools-lin.iso
    mode: 0440

- name: Mount DVD read-only
  mount:
    name: /mnt
    src: /root/prl-tools-lin.iso
    fstype: iso9660
    opts: ro
    state: present

#- name: Rebuild kernel
#  command: "mkinitcpio -p linux"

#- name:  create link to python
#  file: src=/usr/lib/systemd/scripts/
#        dest=/etc/init.d
#        state=link

#- name:  create link to python
#  file: src=/usr/bin/python2
#        dest=/usr/local/bin/python
#        state=link
