---

- name: Set hostname
  hostname:
    name: mothership

- name: Set timezone
  file:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
    state: link

- name: Rebuild kernel
  command: mkinitcpio -p linux

- name: Start services dhcpcd
  service:
    name: dhcpcd
    state: started
    enabled: yes

- name: configure pacman
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    force: yes

- name: command2
  command: "yaourt -S hawaii-meta-git --noconfirm"