---

# Установаю имя хоста
- name: Set hostname
  hostname:
    name: mothership

# Задаю часовой пояс
- name: Set timezone
  file:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime
    state: link
