### AUR
- name: Add archlinuxfr repository to pacman
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"

- name: Install yaourt
  pacman:
    name: "yaourt"
    state: "present"
    update_cache: yes

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - yaourt
    - git
    - wget
    - openssh