- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    force: yes

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - yaourt
    - git
    - wget
    - openssh