---

- name: Install
  pacman:
    name: "docker"
    state: "present"
    update_cache: yes
  sudo: true

- name: Adding existing user "admin" to group docker
  user:
    name: admin
    groups: docker
    append: yes

- name: Start services docker
  service:
    name: "docker"
    state: "started"
    enabled: yes
  sudo: true