---

- name: Install
  pacman:
    name: "docker"
    state: "present"
    update_cache: yes
  sudo: true

- name: Start services docker
  service:
    name: "docker"
    state: "started"
    enabled: yes
  sudo: true