---

- name: Install
  pacman:
    name: "docker"
    state: "present"
    update_cache: yes
  sudo: true

- name: Start services docker
  service:
    name: "docker"
    enabled: yes
  sudo: true

- name: Adding existing user "system" to group docker
  shell: "gpasswd -a system docker"
  sudo: true

- name: Start docker container
  copy:
    src: "ui-for-docker.service"
    dest: "/etc/systemd/system/ui-for-docker.service"
  sudo: true

- name: Autorun docker container
  service:
    name: "ui-for-docker.service"
    enabled: yes
  sudo: true