---

- name: Install
  pacman:
    name: "docker"
    state: "present"
    update_cache: yes
  sudo: true

- name: Install docker-compose
  pip:
    name: docker-compose
  sudo: true

- name: Add /usr/share/bash-completion/completions/docker-compose
  shell: "curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /usr/share/bash-completion/completions/docker-compose"
  sudo: true

- name: Adding existing user "admin" to group docker
  user:
    name: admin
    groups: docker
    append: yes

- name: Start services docker
  service:
    name: "docker"
    state: "started"
    enabled: yes
  sudo: true