---


- name: postinstall-verify | Set timezone
  file:
    src: "/usr/share/zoneinfo/Europe/Moscow"
    dest: "/etc/localtime"
    state: "link"
  sudo: true

- name: postinstall-verify | Config /etc/locale.gen
  lineinfile:
    dest: "/etc/locale.gen"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: "present"
  with_items:
    - { line: 'en_US.UTF-8 UTF-8', regexp: '^#en_US.UTF-8 UTF-8' }
    - { line: 'ru_RU.UTF-8 UTF-8', regexp: '^#ru_RU.UTF-8 UTF-8' }
  sudo: true

- name: postinstall-verify | Generate locale
  command: "locale-gen"
  sudo: true

- name: postinstall-verify | Config /etc/locale.conf
  lineinfile:
    dest: "/etc/locale.conf"
    line: 'LANG="ru_RU.UTF-8"'
    state: "present"
  sudo: true

- name: postinstall-verify | Install base packages
  pacman:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - base
    - base-devel
    - grub
    - git
    - ansible
  sudo: true

- name: postinstall-verify | Rebuild kernel
  command: "mkinitcpio -p linux"
  sudo: true

- name: postinstall-verify | Start services dhcpcd
  service:
    name: "dhcpcd"
    state: "started"
    enabled: yes
  sudo: true