---

- name: building-system | Update Arch
  pacman:
    update_cache: yes
    upgrade: yes
  sudo: true

- name: building-system | Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - base
    - base-devel
    - grub
    - git
    - ansible
    - linux-headers
    - cmake
    - python2
  sudo: true