---

- name: building-system | Install base (all) packages for bulding
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items:
    - linux-headers
    - cmake
    - python
    - python2
    - python-pip
    - python2-pip
  sudo: true
