---

- name: ansible | Create link to init.d
  file:
    src: "/usr/lib/systemd/scripts/"
    dest: "/etc/init.d"
    state: "link"
  sudo: true

- name: ansible | Gen facts
  shell: "ansible -m setup all -u mothership > /etc/ansible/facts.yml"
  sudo: true