---

- name: Set hostname
  hostname:
    name: mothership

- name: Set timezone
  file:
    src: "/usr/share/zoneinfo/Europe/Moscow"
    dest: "/etc/localtime"
    state: "link"

- name: Config /etc/locale.gen
  lineinfile:
    dest: "/etc/locale.gen"
    state: "present"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { line: "en_US.UTF-8 UTF-8", regexp: "^#en_US.UTF-8 UTF-8" }
    - { line: "ru_RU.UTF-8 UTF-8", regexp: "^#ru_RU.UTF-8 UTF-8" }

- name: Generate locale
  command: "locale-gen"

- name: Config /etc/locale.conf
  lineinfile:
    dest: "/etc/locale.conf"
    state: "present"
    line: 'LANG="ru_RU.UTF-8"'

- name: Rebuild kernel
  command: "mkinitcpio -p linux"

- name: Start services dhcpcd
  service:
    name: dhcpcd
    state: started
    enabled: yes